/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import * as vscode from 'vscode';
import { generateUuid } from './uuid';

/**
 * View type that uniquely identifies the Mermaid chat output renderer.
 */
const viewType = 'vscode.chatMermaidDiagram';

/**
 * Mime type used to identify Mermaid diagram data in chat output.
 */
const mime = 'text/vnd.mermaid';

/**
 * Patterns to detect different Mermaid diagram types.
 */
const mermaidPatterns = [
	/^flowchart(\s+(TB|TD|BT|RL|LR))?/i,
	/^graph(\s+(TB|TD|BT|RL|LR))?/i,
	/^sequenceDiagram/i,
	/^classDiagram/i,
	/^stateDiagram(-v2)?/i,
	/^erDiagram/i,
	/^gantt/i,
	/^pie(\s+showData)?/i,
	/^mindmap/i,
	/^timeline/i,
	/^journey/i,
	/^gitGraph/i,
	/^C4Context/i,
	/^C4Container/i,
	/^C4Component/i,
	/^C4Dynamic/i,
	/^C4Deployment/i,
	/^requirementDiagram/i,
	/^quadrantChart/i,
	/^sankey-beta/i,
	/^xychart-beta/i,
	/^block-beta/i,
];

/**
 * Check if the first line matches any known Mermaid diagram type.
 */
function isMermaidDiagram(firstLine: string): boolean {
	const trimmed = firstLine.trim();
	return mermaidPatterns.some(pattern => pattern.test(trimmed));
}

/**
 * Basic validation of the mermaid code structure.
 */
function validateMermaidStructure(code: string): boolean {
	const lines = code.trim().split('\n').filter(l => l.trim().length > 0);
	if (lines.length < 2) {
		return false;
	}
	if (!isMermaidDiagram(lines[0])) {
		return false;
	}
	const contentLines = lines.slice(1).filter(l => !l.trim().startsWith('%%'));
	return contentLines.length > 0;
}

export function activate(context: vscode.ExtensionContext) {

	// Register tools
	context.subscriptions.push(
		vscode.lm.registerTool<{ markup: string }>('renderMermaidDiagram', {
			invoke: async (options, _token) => {
				const sourceCode = options.input.markup;
				return writeMermaidToolOutput(sourceCode);
			},
		})
	);

	// Register the chat output renderer for Mermaid diagrams.
	// This will be invoked with the data generated by the tools.
	// It can also be invoked when rendering old Mermaid diagrams in the chat history.
	context.subscriptions.push(
		vscode.chat.registerChatOutputRenderer(viewType, {
			async renderChatOutput({ value }, webview, _ctx, _token) {
				const mermaidSource = new TextDecoder().decode(value);

				// Set the options for the webview
				const mediaRoot = vscode.Uri.joinPath(context.extensionUri, 'chat-webview-out');
				webview.options = {
					enableScripts: true,
					localResourceRoots: [mediaRoot],
				};

				// Set the HTML content for the webview
				const nonce = generateUuid();
				const mermaidScript = vscode.Uri.joinPath(mediaRoot, 'index.js');

				webview.html = `
					<!DOCTYPE html>
					<html lang="en">

					<head>
						<meta charset="UTF-8">
						<meta name="viewport" content="width=device-width, initial-scale=1.0">
						<title>Mermaid Diagram</title>
						<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src ${webview.cspSource} 'nonce-${nonce}'; style-src 'self' 'unsafe-inline';" />
					</head>

					<body>
						<pre class="mermaid">
							${escapeHtmlText(mermaidSource)}
						</pre>

						<script type="module" nonce="${nonce}" src="${webview.asWebviewUri(mermaidScript)}"></script>
					</body>
					</html>`;
			},
		}));

	// Register the chat code block renderer for Mermaid diagrams.
	// This renders ```mermaid code blocks directly in chat responses.
	const codeBlockRenderer: vscode.ChatCodeBlockRenderer = {
		shouldRenderCodeBlock(codeBlockContext, _token) {
			const code = codeBlockContext.code.trim();
			const languageId = codeBlockContext.languageId.toLowerCase();

			// Case 1: Language is explicitly mermaid
			if (languageId === 'mermaid') {
				return { shouldRender: validateMermaidStructure(code) };
			}

			// Case 2: Check if content looks like Mermaid (for untagged code blocks)
			const firstLine = code.split('\n')[0].trim();
			if (isMermaidDiagram(firstLine)) {
				return { shouldRender: validateMermaidStructure(code) };
			}

			return { shouldRender: false };
		},

		async renderCodeBlock(codeBlockContext, webview, _token) {
			webview.options = {
				enableScripts: true
			};
			webview.html = getMermaidCodeBlockWebviewContent(codeBlockContext.code);
		}
	};

	context.subscriptions.push(
		vscode.chat.registerChatCodeBlockRenderer('vscode.mermaidCodeBlock', codeBlockRenderer)
	);
}


function writeMermaidToolOutput(sourceCode: string): vscode.LanguageModelToolResult {
	// Expose the source code as a tool result for the LM
	const result = new vscode.LanguageModelToolResult([
		new vscode.LanguageModelTextPart(sourceCode)
	]);

	// And store custom data in the tool result details to indicate that a custom renderer should be used for it.
	// In this case we just store the source code as binary data.

	// Add cast to use proposed API
	(result as vscode.ExtendedLanguageModelToolResult2).toolResultDetails2 = {
		mime,
		value: new TextEncoder().encode(sourceCode),
	};

	return result;
}

function escapeHtmlText(str: string): string {
	return str
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;');
}

/**
 * Generate webview HTML content for rendering Mermaid diagrams in code blocks.
 */
function getMermaidCodeBlockWebviewContent(mermaidCode: string): string {
	const escapedCode = mermaidCode
		.replace(/\\/g, '\\\\')
		.replace(/`/g, '\\`')
		.replace(/\$/g, '\\$');

	const htmlEscapedCode = mermaidCode
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');

	return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Mermaid Diagram</title>
	<style>
		* { margin: 0; padding: 0; box-sizing: border-box; }
		html, body {
			background: var(--vscode-editor-background, #1e1e1e);
			min-height: 200px;
			overflow: hidden;
		}
		body {
			padding: 16px;
			font-family: var(--vscode-font-family, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif);
		}
		#diagram-container {
			background: #ffffff;
			border-radius: 8px;
			padding: 20px;
			display: flex;
			justify-content: center;
			align-items: center;
			min-height: 150px;
			overflow: auto;
			position: relative;
			cursor: grab;
		}
		#diagram-container.panning { cursor: grabbing; }
		#diagram-wrapper {
			display: inline-block;
			transform-origin: center center;
			transition: transform 0.1s ease-out;
		}
		#diagram {
			max-width: 100%;
			opacity: 0;
			transition: opacity 0.2s ease-in;
			user-select: none;
		}
		#diagram.visible { opacity: 1; }
		.loading {
			color: #666;
			font-size: 14px;
			display: flex;
			align-items: center;
			gap: 8px;
			position: absolute;
		}
		.loading::before {
			content: '';
			width: 16px;
			height: 16px;
			border: 2px solid #ddd;
			border-top-color: #3c8dbc;
			border-radius: 50%;
			animation: spin 1s linear infinite;
		}
		@keyframes spin { to { transform: rotate(360deg); } }
		.error-container { width: 100%; }
		.error-message {
			color: #c00;
			background: #fee;
			padding: 8px 12px;
			border-radius: 4px 4px 0 0;
			font-size: 12px;
			border-bottom: 1px solid #fcc;
		}
		.fallback-code {
			background: #2d2d2d;
			color: #d4d4d4;
			padding: 12px;
			border-radius: 0 0 4px 4px;
			font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
			font-size: 13px;
			white-space: pre-wrap;
			overflow-x: auto;
			line-height: 1.4;
		}
		.header {
			color: var(--vscode-foreground, #cccccc);
			font-size: 12px;
			margin-bottom: 8px;
			display: flex;
			align-items: center;
			gap: 6px;
		}
		.header svg { width: 16px; height: 16px; }
		.header.error-header { color: #c00; }
	</style>
</head>
<body>
	<div class="header" id="header">
		<svg viewBox="0 0 24 24" fill="currentColor">
			<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
		</svg>
		<span id="header-text">Mermaid Diagram</span>
	</div>
	<div id="diagram-container">
		<div class="loading" id="loading">Rendering diagram...</div>
		<div id="diagram-wrapper">
			<div id="diagram"></div>
		</div>
	</div>
	<script>
		const mermaidCode = \`${escapedCode}\`;
		const originalCode = \`${htmlEscapedCode}\`;

		function loadMermaid() {
			return new Promise((resolve, reject) => {
				const script = document.createElement('script');
				script.src = 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js';
				script.onload = resolve;
				script.onerror = reject;
				document.head.appendChild(script);
			});
		}

		async function renderDiagram() {
			const container = document.getElementById('diagram');
			const diagramWrapper = document.getElementById('diagram-wrapper');
			const diagramContainer = document.getElementById('diagram-container');
			const loadingEl = document.getElementById('loading');
			const header = document.getElementById('header');
			const headerText = document.getElementById('header-text');

			try {
				await loadMermaid();
				mermaid.initialize({
					startOnLoad: false,
					theme: 'default',
					securityLevel: 'loose',
					flowchart: { useMaxWidth: true, htmlLabels: true, curve: 'basis' }
				});

				const { svg } = await mermaid.render('mermaid-svg', mermaidCode);
				container.innerHTML = svg;
				if (loadingEl) loadingEl.style.display = 'none';
				container.classList.add('visible');
				initZoomAndPan(diagramWrapper, diagramContainer);
			} catch (error) {
				header.classList.add('error-header');
				headerText.textContent = 'Mermaid Diagram (Parse Error)';
				diagramContainer.style.background = 'transparent';
				diagramContainer.style.padding = '0';
				container.innerHTML = \`
					<div class="error-container">
						<div class="error-message">⚠ \${error.message || 'Failed to parse diagram'}</div>
						<pre class="fallback-code">\${originalCode}</pre>
					</div>
				\`;
				if (loadingEl) loadingEl.style.display = 'none';
				container.classList.add('visible');
			}
		}

		function initZoomAndPan(wrapper, container) {
			let scale = 1, isPanning = false, startX = 0, startY = 0, translateX = 0, translateY = 0;

			container.addEventListener('wheel', (e) => {
				e.preventDefault();
				const delta = e.deltaY;
				const newScale = delta > 0 ? scale * 0.9 : scale * 1.1;
				scale = Math.min(Math.max(0.5, newScale), 3);
				updateTransform();
			}, { passive: false });

			container.addEventListener('mousedown', (e) => {
				isPanning = true;
				startX = e.clientX - translateX;
				startY = e.clientY - translateY;
				container.classList.add('panning');
			});

			container.addEventListener('mousemove', (e) => {
				if (!isPanning) return;
				translateX = e.clientX - startX;
				translateY = e.clientY - startY;
				updateTransform();
			});

			container.addEventListener('mouseup', () => {
				isPanning = false;
				container.classList.remove('panning');
			});

			container.addEventListener('mouseleave', () => {
				isPanning = false;
				container.classList.remove('panning');
			});

			container.addEventListener('dblclick', () => {
				scale = 1;
				translateX = 0;
				translateY = 0;
				updateTransform();
			});

			function updateTransform() {
				wrapper.style.transform = \`translate(\${translateX}px, \${translateY}px) scale(\${scale})\`;
			}
		}

		requestAnimationFrame(() => {
			if (document.readyState === 'loading') {
				document.addEventListener('DOMContentLoaded', renderDiagram);
			} else {
				renderDiagram();
			}
		});
	</script>
</body>
</html>`;
}
